# coding: utf-8

"""
    StreetSpectra API

    API description for StreetSpectra project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jgcasta@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_user(self):
        """Test case for add_new_user

        Create user data  # noqa: E501
        """
        pass

    def test_edit_user_data(self):
        """Test case for edit_user_data

        Edit user data  # noqa: E501
        """
        pass

    def test_get_history_data_post(self):
        """Test case for get_history_data_post

        Retrieve history data for a user  # noqa: E501
        """
        pass

    def test_get_map_distribution_post(self):
        """Test case for get_map_distribution_post

        Retrieve map data distribution  # noqa: E501
        """
        pass

    def test_get_spectrum_data_post(self):
        """Test case for get_spectrum_data_post

        Retrieve data from a single spectrum  # noqa: E501
        """
        pass

    def test_get_user_data(self):
        """Test case for get_user_data

        Retrieve user data  # noqa: E501
        """
        pass

    def test_get_users_ranking_post(self):
        """Test case for get_users_ranking_post

        Retrieve ranking of users  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        User login  # noqa: E501
        """
        pass

    def test_send_spectrum_data_post(self):
        """Test case for send_spectrum_data_post

        Send spectrum metadata  # noqa: E501
        """
        pass

    def test_send_spectrum_img_post(self):
        """Test case for send_spectrum_img_post

        Send spectrum image file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
