# coding: utf-8

"""
    StreetSpectra API

    API description for StreetSpectra project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jgcasta@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.request_map_distribution import RequestMapDistribution  # noqa: E501
from swagger_client.rest import ApiException


class TestRequestMapDistribution(unittest.TestCase):
    """RequestMapDistribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestMapDistribution(self):
        """Test RequestMapDistribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.request_map_distribution.RequestMapDistribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
