# coding: utf-8

# flake8: noqa
"""
    StreetSpectra API

    API description for StreetSpectra project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jgcasta@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.get_spectrum_data import GetSpectrumData
from swagger_client.models.login import Login
from swagger_client.models.request_map_distribution import RequestMapDistribution
from swagger_client.models.response import Response
from swagger_client.models.response_list_spectra import ResponseListSpectra
from swagger_client.models.spectrum_data import SpectrumData
from swagger_client.models.user_data import UserData
from swagger_client.models.user_ranking import UserRanking
